### ISSUE TITLE
Componente em React

### ISSUE THREAD

**Issue by guilhermemauro** [clicksign/embedded#10]
A ideia é discutir os caminhos para criar para portar a funcionalidade em um componente react js. Ainda não encontrei nada sobre o tema.

**Comment by lucastozze** [comment]
@guilhermemauro Agradecemos sua sugestão e estamos analisando internamente.
Caso queira, pode entrar em contato conosco através do nosso e-mail ajuda@clicksign.com para podermos entendermos melhor seu _feedback_.

Ficamos à disposição!
