### ISSUE TITLE
Uso do método "on"

### ISSUE THREAD

**Issue by AdeilsonSilvaBW** [clicksign/embedded#9]
Olá, baixando o exemplo que vocês disponibilizaram e executando, os método on "loaded" e "signed" não estão gerando o console.log vocês sabem me dizer o porque disso?
Muito obrigado desde já!

**Comment by lucastozze** [comment]
Adeilson, boa tarde,

Tudo bem?

Geralmente isso ocorre quando a URL da página onde o container será exibido não está explicitado no `Widget.origin`.

De todo modo, para podermos melhor lhe auxiliar, poderia nos encaminhar via e-mail o payload da instalação do Widget para investigarmos o caso?

Nosso suporte pode ser contato de modo mais rápido através do endereço ajuda@clicksign.com.

Fico à disposição.

Atenciosamente,

**Comment by AdeilsonSilvaBW** [comment]
Obrigado pelo retorno Lucas, vou seguir pelo e-mail então!
